### ISSUE TITLE
Crashing.

### ISSUE THREAD

**Issue by vishuhm911** [AndroidDeveloperLB/AutoFitTextView#36]
i am getting 

java.lang.StringIndexOutOfBoundsException: length=379; index=379
                                                                       at java.lang.String.charAt(Native Method)
                                                                       at com.lb.auto_fit_textview.AutoResizeTextView$1.onTestSize(AutoResizeTextView.java:89)
                                                                       at com.lb.auto_fit_textview.AutoResizeTextView.binarySearch(AutoResizeTextView.java:227)
                                                                       at com.lb.auto_fit_textview.AutoResizeTextView.superSetTextSize(AutoResizeTextView.java:219)
                                                                       at com.lb.auto_fit_textview.AutoResizeTextView.adjustTextSize(AutoResizeTextView.java:213)
                                                                       at com.lb.auto_fit_textview.AutoResizeTextView.onSizeChanged(AutoResizeTextView.java:251)

**Comment by vishuhm911** [comment]
New line character in the end causes the crash .

New line character in the middle will not resize the text.

**Comment by AndroidDeveloperLB** [comment]
So you've found out how to fix it?
